version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    container_name: telegramstyle-app
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8443
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DOMAIN=${DOMAIN}
      - APP_URL=${APP_URL}
    volumes:
      - ../server:/app
      - /app/node_modules
      - ../ssl:/app/ssl:ro
      - ../client/public:/app/public:ro
    ports:
      - "8080:80"
      - "8443:8443"
    networks:
      - telegramstyle-network

networks:
  telegramstyle-network:
    driver: bridge

volumes:
  mongodb_data: 